###
POST http://localhost:8080/api/libraries
Content-Type: application/json

{
  "name": "Libri",
  "capacity": 10000
}

###
POST http://localhost:8080/api/libraries
Content-Type: application/json

{
  "name": "Readwell",
  "capacity": 1000
}

###
POST http://localhost:8080/api/libraries
Content-Type: application/json

{
"name": "NewOne",
"capacity": 5000
}

###
GET http://localhost:8080/api/libraries/Libri

###
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "author": "Robert C. Martin",
  "title": "Clean Code",
  "bookType": "SCIENCE",
  "libraryName": "Libri"
}

###
POST localhost:8080/api/books/batch
Content-Type: application/json

[
    {
      "title": "Clean Code",
      "author": "Robert C. Martin",
      "bookType": "SCIENCE",
      "libraryName": "Readwell"
    },
    {
      "title": "Effective Java",
      "author": "Joshua Bloch",
      "bookType": "SCIENCE",
      "libraryName": "Readwell"
    },
    {
      "title": "To Kill a Mockingbird",
      "author": "Harper Lee",
      "bookType": "FICTION",
      "libraryName": "Readwell"
    },
    {
      "title": "The Hobbit",
      "author": "J.R.R. Tolkien",
      "bookType": "FICTION",
      "libraryName": "Readwell"
    },
    {
      "title": "Harry Potter and the Philosopher's Stone",
      "author": "J.K. Rowling",
      "bookType": "CHILDREN",
      "libraryName": "Readwell"
    },
    {
      "title": "Sapiens",
      "author": "Yuval Noah Harari",
      "bookType": "NON_FICTION",
      "libraryName": "Readwell"
    }
]


###
POST http://localhost:8080/api/books/batch
Content-Type: application/json

[
  {
    "title": "Spring in Action",
    "author": "Craig Walls",
    "bookType": "SCIENCE",
    "libraryName": "Libri"
  },
  {
    "title": "Design Patterns",
    "author": "Erich Gamma",
    "bookType": "SCIENCE",
    "libraryName": "Libri"
  },
  {
    "title": "1984",
    "author": "George Orwell",
    "bookType": "FICTION",
    "libraryName": "Libri"
  },
  {
    "title": "The Pragmatic Programmer",
    "author": "Andrew Hunt",
    "bookType": "SCIENCE",
    "libraryName": "Libri"
  },
  {
    "title": "The Little Prince",
    "author": "Antoine de Saint-Exupéry",
    "bookType": "CHILDREN",
    "libraryName": "Libri"
  },
  {
    "title": "Thinking, Fast and Slow",
    "author": "Daniel Kahneman",
    "bookType": "NON_FICTION",
    "libraryName": "Libri"
  }
]

###
GET http://localhost:8080/api/books/The Little Prince

###
GET http://localhost:8080/api/books?title=Clean%20Code

###
POST http://localhost:8080/api/books/add-to-library
Content-Type: application/json

  {
    "title": "Clean Code",
    "libraryName": "Readwell"
  }